package com.example.kehtolaulu.nanoblogs.test;

import com.example.kehtolaulu.nanoblogs.test.stories.MyProfilePage;
import com.example.kehtolaulu.nanoblogs.test.stories.NewStoryPage;
import com.example.kehtolaulu.nanoblogs.test.stories.StoryData;
import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.assertTrue;

public class DeleteStoryTest extends AuthenticatedTest {
    private MyProfilePage myProfilePage;
    private static NewStoryPage storyPage;

    @Before
    public void setUp() {
        myProfilePage = new MyProfilePage();
        storyPage = new NewStoryPage();
        storyPage.visit();
        storyPage.createStory(new StoryData("This story was generated by test!"));
    }

    @Test
    public void testDelete() {
        myProfilePage.visit();
        boolean result = myProfilePage.deleteFirstStory();
        assertTrue(result);
    }
}
