package com.example.kehtolaulu.nanoblogs.test;

import com.example.kehtolaulu.nanoblogs.test.stories.NewStoryPage;
import com.example.kehtolaulu.nanoblogs.test.stories.StoryData;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

public class StoryCreationTest extends AuthenticatedTest {
    private static NewStoryPage storyPage;
    private StoryData story;

    @BeforeClass
    public static void init() {
        storyPage = new NewStoryPage();
    }

    @Before
    public void prepareData() {
        story = new StoryData("Hello, world. This story was generated by test!");
    }

    @Test
    public void testStoryCreation() {
        storyPage.open();
        storyPage.createStory(story);
    }
}
