package com.example.kehtolaulu.nanoblogs.test;

import com.example.kehtolaulu.nanoblogs.test.stories.MyProfilePage;
import com.example.kehtolaulu.nanoblogs.test.stories.NewStoryPage;
import com.example.kehtolaulu.nanoblogs.test.stories.StoryData;
import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.assertTrue;

public class StoryEditTest extends AuthenticatedTest {
    private MyProfilePage storyPage;
    private StoryData storyData = new StoryData("This story was edited by test");

    @Before
    public void setUp() {
        storyPage = new MyProfilePage();
        NewStoryPage newStoryPage = new NewStoryPage();
        newStoryPage.visit();
        newStoryPage.createStory(new StoryData("This story was generated by test!"));
    }

    @Test
    public void testDelete() {
        storyPage.visitFirst();
        storyPage.editStory(storyData);
        assertTrue("Story updated.", storyPage.hasStory(storyData));
    }
}
